import { readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname, basename } from 'node:path';
import { createHash } from 'node:crypto';
const [input, notes] = process.argv.slice(2);
if (!input || !notes?.trim()) throw new Error('Usage: node e2e/demo/approve.mjs <video.webm> "Visual review notes"');
const video = resolve(input), folder = dirname(video);
const playback = JSON.parse(await readFile(resolve(folder, 'review/playback.json')));
const sha256 = createHash('sha256').update(await readFile(video)).digest('hex');
if (!playback.decodedToEnd || playback.sha256 !== sha256) throw new Error('Review this exact video before approval');
await writeFile(resolve(folder, 'review/approved.json'), JSON.stringify({ slug: basename(video, '.webm'), sha256, notes, reviewedAt: new Date().toISOString() }, null, 2));
