<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>faithtech-admin</ToolCommandName>
    <PackageId>FaithTechTorontoAiBuildEvent.Provisioning</PackageId>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FaithTechTorontoAiBuildEvent.Infrastructure\FaithTechTorontoAiBuildEvent.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
</Project>
