<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../FaithTechTorontoAiBuildEvent.Infrastructure/FaithTechTorontoAiBuildEvent.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
</Project>
